install.packages("dplyr", dependency=TRUE)
library(dplyr)
input_data <- read.csv("Sample_Data/femaleMiceWeights.csv")
c <- filter(input_data, Diet=="chow")
print(c)
bodyweight <- select(input_data, Bodyweight)
print(bodyweight)

sleep_data <- read.csv("Sample_Data/msleep_ggplot2.csv")
class(sleep_data)
primates <- filter(sleep_data, order=="Primates")
nrow(primates)
class(primates)
pst <- select(primates, sleep_total) 
class(pst)
unlist(pst) %>% mean()
filter(sleep_data, order=="Primates") %>% summarize(mean=mean(sleep_total))
